### ISSUE TITLE
Readme needs updating to clarify pre-registry scan vs regular scan

### ISSUE THREAD

**Issue by marykay25** [jenkinsci/deepsecurity-smartcheck-plugin#1]
Hello,

can you rework the readme to clarify that you can do pre-registry or post registry scanning (toward the top) and then show the code needed for each?  Right now it looks like this section is needed for both:

withCredentials([
    usernamePassword([
        credentialsId: "example-registry-auth",
        usernameVariable: "REGISTRY_USER",
        passwordVariable: "REGISTRY_PASSWORD",
    ])

**Comment by glb** [comment]
Great suggestion, thanks!
