### ISSUE TITLE
Hi Smartcheck

### ISSUE THREAD

**Issue by James-Quinto** [jenkinsci/deepsecurity-smartcheck-plugin#2]
Hi,

Just a few inquiry

1.Does this string will be used for the smartcheck to connect to the registry?
withCredentials([
    usernamePassword([
        credentialsId: "example-registry-auth",
        usernameVariable: "REGISTRY_USER",
        passwordVariable: "REGISTRY_PASSWORD",

2.If yes,Does the AWS ecr registry credential can be masked by this parameter?

Currently,we were trying to integrate a smartcheck scan with ecr.
We were getting this error
![image](https://user-images.githubusercontent.com/55510655/73104803-42cf0680-3f32-11ea-8b8e-808af713443f.png)

thanks in advance!

**Comment by glb** [comment]
Hi @c0t0d0s1 ! Thanks for your question! 

From the image you pasted, it looks like your `Jenkinsfile` is missing the body of the `withCredentials` call. 

Here's an example that calls `smartcheckScan` and provides ECR credentials, assuming you have created a username+password credential named `example-registry-auth` in Jenkins with an AWS access key ID as the username and the secret key as the password.

```groovy
withCredentials([
    usernamePassword([
        credentialsId: "example-registry-auth",
        usernameVariable: "ACCESS_KEY_ID",
        passwordVariable: "SECRET_ACCESS_KEY",
    ])
]){
    smartcheckScan([
        imageName: "registry.example.com/my-project/my-image",
        smartcheckHost: "smartcheck.example.com",
        smartcheckCredentialsId: "smartcheck-auth",
        imagePullAuth: new groovy.json.JsonBuilder([
            aws: [
                region: "REGION",
                accessKeyID: ACCESS_KEY_ID,
                secretAccessKey: SECRET_ACCESS_KEY,
            ]
        ]).toString(),
    ])
}
```

Some notes:
* Remember to replace `REGION` in this example with the region that you are using for your registry in ECR.
* Also remember to replace the values for `imageName`, `smartcheckHost`, and `smartcheckCredentialsId`.
